# Declara formalmente que estamos usando el proveedor de Python y especificamos una versión
[providers.python]
version = "3.11" # Puedes usar 3.10, 3.11, o 3.12

# Fase de instalación: le decimos cómo instalar las dependencias
[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r backend/requirements.txt"]

# Fase de inicio: le decimos cómo ejecutar la aplicación
[start]
cmd = "gunicorn --chdir backend -w 4 -b 0.0.0.0:3000 app:app"