[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn --chdir backend -w 4 -b 0.0.0.0:3000 app:app"