# Le decimos a Nixpacks que use el "proveedor" de Python
providers = ["python"]

[phases.install]
# Le decimos cómo instalar las dependencias, especificando la ruta correcta
cmds = ["pip install -r backend/requirements.txt"]

[start]
# Usamos --chdir para que gunicorn se mueva al directorio 'backend' antes de ejecutarse
cmd = "gunicorn --workers 4 --bind 0.0.0.0:3000 --chdir backend app:app"